apiVersion: apps/v1
kind: Deployment

metadata:
  name: bookshelf-web
  namespace: bookshelf

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bookshelf-web

  template:
    metadata:
      labels:
        app: bookshelf-web

    spec:
      containers:
        - name: bookshelf-web
          image: bookshelfacr2026.azurecr.io/bookshelf-web:v11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80